// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.example.task_reminder_app;

import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.RetentionPolicy.CLASS;

import android.util.Log;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import io.flutter.plugin.common.BasicMessageChannel;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MessageCodec;
import io.flutter.plugin.common.StandardMessageCodec;
import java.io.ByteArrayOutputStream;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;
import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/** Generated class from Pigeon. */
@SuppressWarnings({"unused", "unchecked", "CodeBlock2Expr", "RedundantSuppression", "serial"})
public class TaskTestModuleNativeInterface {

  /** Error class for passing custom error details to Flutter via a thrown PlatformException. */
  public static class FlutterError extends RuntimeException {

    /** The error code. */
    public final String code;

    /** The error details. Must be a datatype supported by the api codec. */
    public final Object details;

    public FlutterError(@NonNull String code, @Nullable String message, @Nullable Object details) 
    {
      super(message);
      this.code = code;
      this.details = details;
    }
  }

  @NonNull
  protected static ArrayList<Object> wrapError(@NonNull Throwable exception) {
    ArrayList<Object> errorList = new ArrayList<>(3);
    if (exception instanceof FlutterError) {
      FlutterError error = (FlutterError) exception;
      errorList.add(error.code);
      errorList.add(error.getMessage());
      errorList.add(error.details);
    } else {
      errorList.add(exception.toString());
      errorList.add(exception.getClass().getSimpleName());
      errorList.add(
        "Cause: " + exception.getCause() + ", Stacktrace: " + Log.getStackTraceString(exception));
    }
    return errorList;
  }

  @NonNull
  protected static FlutterError createConnectionError(@NonNull String channelName) {
    return new FlutterError("channel-error",  "Unable to establish connection on channel: " + channelName + ".", "");
  }

  @Target(METHOD)
  @Retention(CLASS)
  @interface CanIgnoreReturnValue {}

  /** Generated class from Pigeon that represents data sent in messages. */
  public static final class NativeTaskConfig {
    private @NonNull String reminderTime;

    public @NonNull String getReminderTime() {
      return reminderTime;
    }

    public void setReminderTime(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"reminderTime\" is null.");
      }
      this.reminderTime = setterArg;
    }

    private @NonNull String title;

    public @NonNull String getTitle() {
      return title;
    }

    public void setTitle(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"title\" is null.");
      }
      this.title = setterArg;
    }

    private @NonNull String description;

    public @NonNull String getDescription() {
      return description;
    }

    public void setDescription(@NonNull String setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"description\" is null.");
      }
      this.description = setterArg;
    }

    private @NonNull Long hour;

    public @NonNull Long getHour() {
      return hour;
    }

    public void setHour(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"hour\" is null.");
      }
      this.hour = setterArg;
    }

    private @NonNull Long minute;

    public @NonNull Long getMinute() {
      return minute;
    }

    public void setMinute(@NonNull Long setterArg) {
      if (setterArg == null) {
        throw new IllegalStateException("Nonnull field \"minute\" is null.");
      }
      this.minute = setterArg;
    }

    /** Constructor is non-public to enforce null safety; use Builder. */
    NativeTaskConfig() {}

    @Override
    public boolean equals(Object o) {
      if (this == o) { return true; }
      if (o == null || getClass() != o.getClass()) { return false; }
      NativeTaskConfig that = (NativeTaskConfig) o;
      return reminderTime.equals(that.reminderTime) && title.equals(that.title) && description.equals(that.description) && hour.equals(that.hour) && minute.equals(that.minute);
    }

    @Override
    public int hashCode() {
      return Objects.hash(reminderTime, title, description, hour, minute);
    }

    public static final class Builder {

      private @Nullable String reminderTime;

      @CanIgnoreReturnValue
      public @NonNull Builder setReminderTime(@NonNull String setterArg) {
        this.reminderTime = setterArg;
        return this;
      }

      private @Nullable String title;

      @CanIgnoreReturnValue
      public @NonNull Builder setTitle(@NonNull String setterArg) {
        this.title = setterArg;
        return this;
      }

      private @Nullable String description;

      @CanIgnoreReturnValue
      public @NonNull Builder setDescription(@NonNull String setterArg) {
        this.description = setterArg;
        return this;
      }

      private @Nullable Long hour;

      @CanIgnoreReturnValue
      public @NonNull Builder setHour(@NonNull Long setterArg) {
        this.hour = setterArg;
        return this;
      }

      private @Nullable Long minute;

      @CanIgnoreReturnValue
      public @NonNull Builder setMinute(@NonNull Long setterArg) {
        this.minute = setterArg;
        return this;
      }

      public @NonNull NativeTaskConfig build() {
        NativeTaskConfig pigeonReturn = new NativeTaskConfig();
        pigeonReturn.setReminderTime(reminderTime);
        pigeonReturn.setTitle(title);
        pigeonReturn.setDescription(description);
        pigeonReturn.setHour(hour);
        pigeonReturn.setMinute(minute);
        return pigeonReturn;
      }
    }

    @NonNull
    ArrayList<Object> toList() {
      ArrayList<Object> toListResult = new ArrayList<>(5);
      toListResult.add(reminderTime);
      toListResult.add(title);
      toListResult.add(description);
      toListResult.add(hour);
      toListResult.add(minute);
      return toListResult;
    }

    static @NonNull NativeTaskConfig fromList(@NonNull ArrayList<Object> pigeonVar_list) {
      NativeTaskConfig pigeonResult = new NativeTaskConfig();
      Object reminderTime = pigeonVar_list.get(0);
      pigeonResult.setReminderTime((String) reminderTime);
      Object title = pigeonVar_list.get(1);
      pigeonResult.setTitle((String) title);
      Object description = pigeonVar_list.get(2);
      pigeonResult.setDescription((String) description);
      Object hour = pigeonVar_list.get(3);
      pigeonResult.setHour((Long) hour);
      Object minute = pigeonVar_list.get(4);
      pigeonResult.setMinute((Long) minute);
      return pigeonResult;
    }
  }

  private static class PigeonCodec extends StandardMessageCodec {
    public static final PigeonCodec INSTANCE = new PigeonCodec();

    private PigeonCodec() {}

    @Override
    protected Object readValueOfType(byte type, @NonNull ByteBuffer buffer) {
      switch (type) {
        case (byte) 129:
          return NativeTaskConfig.fromList((ArrayList<Object>) readValue(buffer));
        default:
          return super.readValueOfType(type, buffer);
      }
    }

    @Override
    protected void writeValue(@NonNull ByteArrayOutputStream stream, Object value) {
      if (value instanceof NativeTaskConfig) {
        stream.write(129);
        writeValue(stream, ((NativeTaskConfig) value).toList());
      } else {
        super.writeValue(stream, value);
      }
    }
  }


  /** Asynchronous error handling return type for non-nullable API method returns. */
  public interface Result<T> {
    /** Success case callback method for handling returns. */
    void success(@NonNull T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for nullable API method returns. */
  public interface NullableResult<T> {
    /** Success case callback method for handling returns. */
    void success(@Nullable T result);

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /** Asynchronous error handling return type for void API method returns. */
  public interface VoidResult {
    /** Success case callback method for handling returns. */
    void success();

    /** Failure case callback method for handling errors. */
    void error(@NonNull Throwable error);
  }
  /**
   * Flutter -> Native communication
   * Requires implementation on Native side
   *
   * Generated interface from Pigeon that represents a handler of messages from Flutter.
   */
  public interface TaskTestModuleNative {

    void addNotification(@NonNull NativeTaskConfig task);

    /** The codec used by TaskTestModuleNative. */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    /**Sets up an instance of `TaskTestModuleNative` to handle messages through the `binaryMessenger`. */
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @Nullable TaskTestModuleNative api) {
      setUp(binaryMessenger, "", api);
    }
    static void setUp(@NonNull BinaryMessenger binaryMessenger, @NonNull String messageChannelSuffix, @Nullable TaskTestModuleNative api) {
      messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
      {
        BasicMessageChannel<Object> channel =
            new BasicMessageChannel<>(
                binaryMessenger, "dev.flutter.pigeon.task_reminder_app.TaskTestModuleNative.addNotification" + messageChannelSuffix, getCodec());
        if (api != null) {
          channel.setMessageHandler(
              (message, reply) -> {
                ArrayList<Object> wrapped = new ArrayList<>();
                ArrayList<Object> args = (ArrayList<Object>) message;
                NativeTaskConfig taskArg = (NativeTaskConfig) args.get(0);
                try {
                  api.addNotification(taskArg);
                  wrapped.add(0, null);
                }
 catch (Throwable exception) {
                  wrapped = wrapError(exception);
                }
                reply.reply(wrapped);
              });
        } else {
          channel.setMessageHandler(null);
        }
      }
    }
  }
  /** Generated class from Pigeon that represents Flutter messages that can be called from Java. */
  public static class TaskTestModuleFlutter {
    private final @NonNull BinaryMessenger binaryMessenger;
    private final String messageChannelSuffix;

    public TaskTestModuleFlutter(@NonNull BinaryMessenger argBinaryMessenger) {
      this(argBinaryMessenger, "");
    }
    public TaskTestModuleFlutter(@NonNull BinaryMessenger argBinaryMessenger, @NonNull String messageChannelSuffix) {
      this.binaryMessenger = argBinaryMessenger;
      this.messageChannelSuffix = messageChannelSuffix.isEmpty() ? "" : "." + messageChannelSuffix;
    }

    /**
     * Public interface for sending reply.
     * The codec used by TaskTestModuleFlutter.
     */
    static @NonNull MessageCodec<Object> getCodec() {
      return PigeonCodec.INSTANCE;
    }
    public void updateTask(@NonNull NativeTaskConfig taskArg, @NonNull VoidResult result) {
      final String channelName = "dev.flutter.pigeon.task_reminder_app.TaskTestModuleFlutter.updateTask" + messageChannelSuffix;
      BasicMessageChannel<Object> channel =
          new BasicMessageChannel<>(
              binaryMessenger, channelName, getCodec());
      channel.send(
          new ArrayList<>(Collections.singletonList(taskArg)),
          channelReply -> {
            if (channelReply instanceof List) {
              List<Object> listReply = (List<Object>) channelReply;
              if (listReply.size() > 1) {
                result.error(new FlutterError((String) listReply.get(0), (String) listReply.get(1), listReply.get(2)));
              } else {
                result.success();
              }
            }  else {
              result.error(createConnectionError(channelName));
            } 
          });
    }
  }
}
