// Autogenerated from Pigeon (v22.7.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeTaskConfig {
  var reminderTime: String
  var title: String
  var description: String
  var hour: Int64
  var minute: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeTaskConfig? {
    let reminderTime = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let description = pigeonVar_list[2] as! String
    let hour = pigeonVar_list[3] as! Int64
    let minute = pigeonVar_list[4] as! Int64

    return NativeTaskConfig(
      reminderTime: reminderTime,
      title: title,
      description: description,
      hour: hour,
      minute: minute
    )
  }
  func toList() -> [Any?] {
    return [
      reminderTime,
      title,
      description,
      hour,
      minute,
    ]
  }
}

private class TaskTestModuleNativeProtocolPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeTaskConfig.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class TaskTestModuleNativeProtocolPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeTaskConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TaskTestModuleNativeProtocolPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TaskTestModuleNativeProtocolPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TaskTestModuleNativeProtocolPigeonCodecWriter(data: data)
  }
}

class TaskTestModuleNativeProtocolPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = TaskTestModuleNativeProtocolPigeonCodec(readerWriter: TaskTestModuleNativeProtocolPigeonCodecReaderWriter())
}

/// Flutter -> Native communication
/// Requires implementation on Native side
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TaskTestModuleNative {
  func addNotification(task: NativeTaskConfig) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TaskTestModuleNativeSetup {
  static var codec: FlutterStandardMessageCodec { TaskTestModuleNativeProtocolPigeonCodec.shared }
  /// Sets up an instance of `TaskTestModuleNative` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TaskTestModuleNative?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let addNotificationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.task_reminder_app.TaskTestModuleNative.addNotification\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addNotificationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let taskArg = args[0] as! NativeTaskConfig
        do {
          try api.addNotification(task: taskArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      addNotificationChannel.setMessageHandler(nil)
    }
  }
}
